# Generated by Django 2.2.7 on 2019-12-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191202_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='byline',
            field=models.TextField(default='byline'),
            preserve_default=False,
        ),
    ]
