# Generated by Django 3.0.1 on 2020-01-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20191217_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='imagesmall',
        ),
        migrations.AddField(
            model_name='post',
            name='imagewide',
            field=models.ImageField(default='pic1', upload_to='parking_pics'),
            preserve_default=False,
        ),
    ]
