# Generated by Django 3.0.1 on 2020-01-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200105_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='park_destination',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='park_difficulty',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='park_restrictions',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='park_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
