# Generated by Django 3.0.1 on 2020-01-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200114_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('story', 'story'), ('review', 'review'), ('news', 'news'), ('snack-bar', 'snack-bar')], max_length=30),
        ),
    ]
