# Generated by Django 3.0.1 on 2020-01-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200114_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='head_article_byline_widescreen_margin',
            field=models.CharField(default='0', max_length=4),
        ),
    ]
