# Generated by Django 3.0.1 on 2020-01-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_head_article_byline_widescreen_margin'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='review_location',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='review_restrictions',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='review_snackbar_status',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='review_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
