# Generated by Django 3.0.1 on 2020-01-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_article_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='article_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
