# Generated by Django 3.0.1 on 2020-01-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200123_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='article_id',
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='temp'),
            preserve_default=False,
        ),
    ]
